In [31]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [32]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
#Ans:
type(list_)

list

In [33]:
type(array_list)

numpy.ndarray

In [34]:
#Here we simply get the dfference of types between list_ and array_list. "list_" is a list type and "array_list" is n dimensional array

In [35]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.
#Ans:
for i in list_:
    print(type(i))
    
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [36]:
#Q3. Considering the following changes in the variable, array_list:
#array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.
#Ans:
array_list = np.array(object = list_, dtype = int)

In [37]:
array_list

array([1, 2, 3, 4, 5])

In [38]:
#Here we can see that the elements present in array_list has changed to integer type where the elements under list_ remains string as before.
#The code is :
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [39]:
for i in list_:
    print(type(i))
    
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [40]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [41]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size
#Ans:
num_array.shape

(2, 3)

In [42]:
num_array.size

6

In [43]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#Ans:
array = np.zeros(shape =(3,3))

In [44]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#Ans:
array1 = np.eye(5)

In [48]:
array1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])